[[stacks]]
id = "MyNetwork"
factory = "acru_l.stacks.NetworkStackFactory"
[stacks.options.vpc]
name = "ID"
cidr = "10.12.0.0/16"
export_name = "MyVPC"
[stacks.options.hosted_zone]
domain_name = "quadio.app"
export_name = "MyHostedZone"
use_github_pages = true

[[stacks]]
id = "MyCerts"
factory = "acru_l.stacks.CertificatesStackFactory"
[stacks.options]
hosted_zone_domain_name = "quadio.app"
[[stacks.options.certificates]]
name = "MyCert"
domain_name = "*.quadio.app"
export_name = "MyCertARN"


[[stacks]]
id = "MyEmails"
factory = "acru_l.stacks.EmailsStackFactory"
[stacks.options]
hosted_zone_domain_name = "quadio.app"
emails = ["admin@quadio.app", "help@quadio.app"]

[[stacks]]
id = "DummyDjango"
factory = "acru_l.stacks.LucarioStackFactory"

[stacks.options]
hosted_zone_domain_name = "quadio.app"
cert_export_name = "QaudioAppWildCardCertificate"
version = "0.0.0"
vpc_name = "MyVPC"

[stacks.options.rds_options]
db_name = "test"
db_username = "myusernameiscool"
add_proxy = true
#multi_az = false
#deletion_protection = false
#setup_alarms = false
#instance_class = "BURSTABLE3"
#instance_size = "MICRO"

[stacks.options.service_options]
domain_name = "api.quadio.app"
project_source_path = "./src/"
health_check_url = "https://api.quadio.app/"
secrets = [
    {name = "Boo", arn_key = "boo", password_length = 16, include_space = false, exclude_punctuation = true},
]
local_environment = [
    "FOO"
]
[stacks.options.service_options.environment]
foo = "bar"
WSGI_APPLICATION = "path.to.wsgi.application"

[stacks.options.service_options.pre_deploy_options]
source_path = "./tests/pre_deploy"
properties = {app_label = "db", migration_name = "0001"}
[stacks.options.service_options.post_deploy_options]
source_path = "./tests/post_deploy"
properties = {app_label = "db", migration_name = "0002"}

[[stacks]]
id = "MyUsersService"
factory = "acru_l.stacks.users.UsersStackFactory"
[stacks.options]
export_name = "CoolUsersARN"
[stacks.options.user_pool]
user_pool_name = "CoolUsers"
