name: Action Build

on:
  push:
    branches:
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - LICENSE
      - '**/README.md'
      - .gitignore

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACRUL_CONFIG_PATH: ./tests/fixtures/config/acru-l.toml
  DEPLOY_ID: ${{ github.sha }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          tags: quadiomedia/acru-l:${{ env.RELEASE_VERSION }}
          push: true
  test:
    needs:
      - build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws_region:
          - us-east-1
    steps:
      - uses: actions/checkout@v2
      - name: Synth
        uses: ./
        with:
          subcommand: synthesize
        env:
          AWS_REGION: ${{ matrix.aws_region }}
          ACRUL_CONFIG_PATH: ./tests/fixtures/config/lucario.toml
          ACRUL_SECTION: tool.acru-l
      - name: deploy
        uses: ./
        with:
          subcommand: deploy -f
        env:
          AWS_REGION: ${{ matrix.aws_region }}
      - name: destroy stack
        uses: ./
        with:
          subcommand: destroy -f
        env:
          AWS_REGION: ${{ matrix.aws_region }}
