name: Action Build

on:
  push:
    branches:
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - LICENSE
      - '**/README.md'
      - .gitignore

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACRUL_CONFIG_PATH: ./tests/fixtures/config/acru-l.toml
  DEPLOY_ID: ${{ github.sha }}


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws_region:
          - us-east-1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-node@v2
        with:
          node-version: 12
#      - name: Synth
#        uses: ./
#        with:
#          subcommand: synthesize
#        env:
#          AWS_REGION: ${{ matrix.aws_region }}
#          ACRUL_CONFIG_PATH: ./tests/fixtures/config/lucario.toml
#          ACRUL_SECTION: tool.acru-l
#          FOO: bar
      - name: deploy
        uses: ./
        with:
          subcommand: deploy -f
        env:
          AWS_REGION: ${{ matrix.aws_region }}
      - name: destroy stack
        uses: ./
        with:
          subcommand: destroy -f
        env:
          AWS_REGION: ${{ matrix.aws_region }}
